/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-secondary-fixed-variant": "#004882",
        "tertiary-fixed": "#ffddb8",
        "on-primary-fixed": "#002109",
        "on-primary": "#003915",
        "surface-bright": "#353940",
        "secondary-container": "#0071c7",
        "on-surface-variant": "#bccbb9",
        "tertiary-container": "#ef9900",
        "surface-container-highest": "#31353c",
        "primary-fixed-dim": "#4ae176",
        "on-surface": "#dfe2eb",
        "on-primary-container": "#004b1e",
        "primary": "#4be277",
        "secondary": "#a2c9ff",
        "background": "#10141a",
        "surface-container-lowest": "#0a0e14",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#005321",
        "on-secondary-container": "#f0f4ff",
        "tertiary-fixed-dim": "#ffb95f",
        "tertiary": "#ffba61",
        "surface": "#10141a",
        "surface-container": "#1c2026",
        "outline-variant": "#3d4a3d",
        "on-background": "#dfe2eb",
        "secondary-fixed-dim": "#a2c9ff",
        "on-tertiary-fixed": "#2a1700",
        "secondary-fixed": "#d3e4ff",
        "on-secondary-fixed": "#001c38",
        "primary-fixed": "#6bff8f",
        "surface-variant": "#31353c",
        "primary-container": "#22c55e",
        "inverse-on-surface": "#2d3137",
        "error": "#ffb4ab",
        "inverse-surface": "#dfe2eb",
        "surface-tint": "#4ae176",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#006e2f",
        "on-tertiary-container": "#5c3800",
        "surface-container-high": "#262a31",
        "surface-dim": "#10141a",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#653e00",
        "outline": "#869585",
        "surface-container-low": "#181c22",
        "on-secondary": "#00315c",
        "on-tertiary": "#472a00"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "inset-sm": "0.5rem",
        "inset-md": "0.75rem",
        "inset-lg": "1rem",
        "gutter-spacious": "1.5rem",
        "inset-xl": "1.5rem",
        "gutter-normal": "1rem",
        "inset-xs": "0.25rem",
        "gutter-compact": "0.5rem",
        "pane-gap": "0.25rem"
      },
      "fontFamily": {
        "headline-md": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "label-sm": ["JetBrains Mono"],
        "code-lg": ["JetBrains Mono"],
        "headline-xl": ["Inter"],
        "headline-xl-mobile": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["JetBrains Mono"],
        "code-sm": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-sm": ["Inter"]
      },
      "fontSize": {
        "headline-md": ["18px", {"lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "code-md": ["13px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-sm": ["10px", {"lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "600"}],
        "code-lg": ["14px", {"lineHeight": "22px", "fontWeight": "500"}],
        "headline-xl": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-xl-mobile": ["26px", {"lineHeight": "34px", "letterSpacing": "-0.015em", "fontWeight": "700"}],
        "headline-lg-mobile": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "code-sm": ["11px", {"lineHeight": "16px", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600"}],
        "headline-sm": ["15px", {"lineHeight": "20px", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
